server:
  port: 8081

spring:
  redis:
    database: 0
    host: 10.105.107.10
    port: 6379
#    url: redis://redis-service
#    port: 6379
    timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  server:
    port: 8998
