server:
  port: 8081

spring:
  redis:
    database: 0
    url: redis://redis-service
    timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  server:
    port: 8998
