apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ratelimit-service
  name: ratelimit-service
  namespace: nju07
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit-service
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: ratelimit-service
    spec:
      containers:
        - image: harbor.edu.cn/nju07/ratelimit-service:{VERSION}
          name: ratelimit-service
      imagePullSecrets:
        - name: nju07
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit-service
  namespace: nju07
  labels:
    app: ratelimit-service
spec:
  type: NodePort
  selector:
    app: ratelimit-service
  ports:
    - name: tcp
      nodePort: 30003
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http
      nodePort: 30004
      protocol: HTTP
      port: 8081
      targetPort: 8081

