apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: nju07
spec:
  type: ClusterIP
  ports:
    - port: 6379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-service
  namespace: nju07
subsets:
  - addresses:
#      - ip: 121.37.67.63
      - ip: 127.0.0.1
    ports:
      - port: 6379

#apiVersion: v1
#kind: Service
#metadata:
#  name: redis-service
#  namespace: nju07
#spec:
#  type: ExternalName
#  externalName: localhost
##  externalName: 121.37.67.63
#  ports:
#    - port: 6379