apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: nju07
subsets:
  - addresses:
      - ip: 121.37.67.63
    ports:
      - port: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nju07
spec:
  clusterIP: 172.17.0.100
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP